# Generated by Django 5.1 on 2024-09-18 04:20

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashCountSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('voucher_number', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('payin', 'Payin'), ('payout', 'Payout')], max_length=10)),
            ],
            options={
                'verbose_name': 'Cash Count Sheet',
                'verbose_name_plural': 'Cash Count Sheets',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('debit_credit', models.CharField(blank=True, choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MainGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitLossShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_no', models.CharField(max_length=100, unique=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('total_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(blank=True, choices=[('profit', 'Profit'), ('lose', 'Lose')], max_length=10)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loss_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShareUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('partners', 'Partners'), ('managements', 'Managements')], max_length=15)),
                ('profitlose_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CashCountSheetItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('currency', models.PositiveIntegerField()),
                ('nos', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions_app.cashcountsheet')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('Sales', 'Sales'), ('Indirect Income', 'Indirect Income')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_statements', to='transactions_app.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='transactions_app.ledger')),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='transactions_app.maingroup'),
        ),
        migrations.AddField(
            model_name='maingroup',
            name='nature_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_groups', to='transactions_app.naturegroup'),
        ),
        migrations.CreateModel(
            name='ShareUserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_lose', models.CharField(choices=[('profit', 'Profit'), ('lose', 'Lose')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('share_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_user_transactions', to='transactions_app.shareusers')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_user_transactions', to='transactions_app.profitlosssharetransaction')),
            ],
        ),
        migrations.CreateModel(
            name='SharePaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('share_user_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='transactions_app.shareusertransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('voucher_no', models.PositiveIntegerField()),
                ('ref_no', models.CharField(blank=True, max_length=15, null=True)),
                ('debit_credit', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='transactions_app.ledger')),
                ('particulars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particulars_transactions', to='transactions_app.ledger')),
            ],
        ),
    ]
