# Generated by Django 5.1 on 2024-09-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('payin', 'Payin'), ('payout', 'Payout')], max_length=10),
        ),
    ]
